DROP TABLE IF EXISTS bins;
CREATE TABLE bins (
  id SERIAL PRIMARY KEY,
  access_code INT NOT NULL DEFAULT 0,
  content TEXT NOT NULL DEFAULT '',
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ON bins (access_code);
CREATE INDEX ON bins (created);
